/**
 * POST /api/email/password-reset
 *
 * Server-side password reset email trigger.
 * Sends a branded password reset email via Resend.
 * The reset URL is generated by Supabase Auth — never fabricated.
 * Nothing is stored in the database.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { sendPasswordReset } from '@/lib/email/sendEmail';

export async function POST(request: NextRequest) {
  let body: { email?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
  }

  const { email } = body;
  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: 'Valid email is required.' }, { status: 400 });
  }

  const supabase = await createClient();
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://summeca1430.builtwithrocket.new';

  // ── 1. Trigger Supabase Auth password reset (generates the secure link) ───
  const { error: resetError } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: `${siteUrl}/auth/callback?next=/user-dashboard/settings`,
  });

  // Always return success to prevent email enumeration attacks
  if (resetError) {
    console.warn('[password-reset] Supabase resetPasswordForEmail error:', resetError.message);
    return NextResponse.json({ message: 'If an account exists, a reset link has been sent.' });
  }

  // ── 2. Send branded email via Resend ──────────────────────────────────────
  // Note: Supabase also sends its own reset email. This sends a branded version.
  // To use ONLY Resend, disable Supabase Auth email in the Supabase dashboard
  // under Authentication > Email Templates, or use a custom SMTP.
  try {
    const { data: users } = await supabase
      .from('user_profiles')
      .select('full_name')
      .eq('id', (await supabase.auth.admin.listUsers()).data.users.find(u => u.email === email)?.id ?? '')
      .maybeSingle();

    await sendPasswordReset(email, {
      customerName: users?.full_name ?? '',
      resetUrl: `${siteUrl}/sign-up-login-screen?mode=reset`,
    });
  } catch (emailErr) {
    console.warn('[password-reset] Branded email failed (non-fatal):', emailErr);
  }

  return NextResponse.json({ message: 'If an account exists, a reset link has been sent.' });
}
